# Generated by Django 5.0.4 on 2024-05-23 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=255)),
                ('salary', models.IntegerField(max_length=50)),
                ('location', models.TextField()),
                ('Experience', models.CharField(choices=[('one year', 'one year'), ('Two year', 'Two year'), ('Three year', 'Three year'), ('Four year', 'Four year'), ('Five year', 'Five year')], max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
