# Generated by Django 5.0.4 on 2024-05-23 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_addjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='addjob',
            old_name='Experience',
            new_name='experience',
        ),
    ]
