# Generated by Django 5.0.4 on 2024-05-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_addnotification_rename_experience_addjob_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
