# Generated by Django 5.0.4 on 2024-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
