# Generated by Django 5.0.4 on 2024-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_complain_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
