# Generated by Django 5.0.4 on 2024-06-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_employee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
    ]
